#!/bin/sh
mkdir ${webapp.nexusWorkLocation}
chown -R ${debian.tomcatUser}.${debian.tomcatGroup} ${webapp.nexusWorkLocation}
echo "Thank you for installing Sonatype Nexus OSS through this debian package!"